version: '2.3'

services:
  bot:
    build: .
    restart: always
    stop_signal: SIGINT
    user: "${USER_UID}:${USER_GID}"
    volumes:
      - ./config.yml:/bot/config.yml:ro
      - ./.db/:/bot/.db:rw
